// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointment_services.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppointmentService = `-- name: CreateAppointmentService :one
INSERT INTO appointment_services (appointment_id, service_name, service_price, design_price) VALUES ($1, $2, $3, $4) RETURNING id, appointment_id, service_name, service_price, design_price, created_at
`

type CreateAppointmentServiceParams struct {
	AppointmentID pgtype.UUID    `json:"appointment_id"`
	ServiceName   string         `json:"service_name"`
	ServicePrice  pgtype.Numeric `json:"service_price"`
	DesignPrice   pgtype.Numeric `json:"design_price"`
}

func (q *Queries) CreateAppointmentService(ctx context.Context, arg CreateAppointmentServiceParams) (AppointmentService, error) {
	row := q.db.QueryRow(ctx, createAppointmentService,
		arg.AppointmentID,
		arg.ServiceName,
		arg.ServicePrice,
		arg.DesignPrice,
	)
	var i AppointmentService
	err := row.Scan(
		&i.ID,
		&i.AppointmentID,
		&i.ServiceName,
		&i.ServicePrice,
		&i.DesignPrice,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAppointmentService = `-- name: DeleteAppointmentService :exec
DELETE FROM appointment_services WHERE id = $1
`

func (q *Queries) DeleteAppointmentService(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAppointmentService, id)
	return err
}

const listAppointmentServicesByAppointment = `-- name: ListAppointmentServicesByAppointment :many
SELECT id, service_name, service_price, design_price
FROM appointment_services
WHERE appointment_id = $1
`

type ListAppointmentServicesByAppointmentRow struct {
	ID           pgtype.UUID    `json:"id"`
	ServiceName  string         `json:"service_name"`
	ServicePrice pgtype.Numeric `json:"service_price"`
	DesignPrice  pgtype.Numeric `json:"design_price"`
}

func (q *Queries) ListAppointmentServicesByAppointment(ctx context.Context, appointmentID pgtype.UUID) ([]ListAppointmentServicesByAppointmentRow, error) {
	rows, err := q.db.Query(ctx, listAppointmentServicesByAppointment, appointmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppointmentServicesByAppointmentRow{}
	for rows.Next() {
		var i ListAppointmentServicesByAppointmentRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceName,
			&i.ServicePrice,
			&i.DesignPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
