// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointment_discounts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppointmentDiscount = `-- name: CreateAppointmentDiscount :one
INSERT INTO appointment_discounts (appointment_id, discount_name, discount_type, discount_value) VALUES ($1, $2, $3, $4) RETURNING id, appointment_id, discount_name, discount_type, discount_value, created_at
`

type CreateAppointmentDiscountParams struct {
	AppointmentID pgtype.UUID    `json:"appointment_id"`
	DiscountName  string         `json:"discount_name"`
	DiscountType  DiscountType   `json:"discount_type"`
	DiscountValue pgtype.Numeric `json:"discount_value"`
}

func (q *Queries) CreateAppointmentDiscount(ctx context.Context, arg CreateAppointmentDiscountParams) (AppointmentDiscount, error) {
	row := q.db.QueryRow(ctx, createAppointmentDiscount,
		arg.AppointmentID,
		arg.DiscountName,
		arg.DiscountType,
		arg.DiscountValue,
	)
	var i AppointmentDiscount
	err := row.Scan(
		&i.ID,
		&i.AppointmentID,
		&i.DiscountName,
		&i.DiscountType,
		&i.DiscountValue,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAppointmentDiscount = `-- name: DeleteAppointmentDiscount :exec
DELETE FROM appointment_discounts WHERE id = $1
`

func (q *Queries) DeleteAppointmentDiscount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAppointmentDiscount, id)
	return err
}

const listAppointmentDiscountsByAppointment = `-- name: ListAppointmentDiscountsByAppointment :many
SELECT id, discount_name, discount_type, discount_value
FROM appointment_discounts
WHERE appointment_id = $1
`

type ListAppointmentDiscountsByAppointmentRow struct {
	ID            pgtype.UUID    `json:"id"`
	DiscountName  string         `json:"discount_name"`
	DiscountType  DiscountType   `json:"discount_type"`
	DiscountValue pgtype.Numeric `json:"discount_value"`
}

func (q *Queries) ListAppointmentDiscountsByAppointment(ctx context.Context, appointmentID pgtype.UUID) ([]ListAppointmentDiscountsByAppointmentRow, error) {
	rows, err := q.db.Query(ctx, listAppointmentDiscountsByAppointment, appointmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppointmentDiscountsByAppointmentRow{}
	for rows.Next() {
		var i ListAppointmentDiscountsByAppointmentRow
		if err := rows.Scan(
			&i.ID,
			&i.DiscountName,
			&i.DiscountType,
			&i.DiscountValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
