// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (client_id, appt_date, notes) VALUES ($1, $2, $3) RETURNING id, client_id, appt_date, appt_status, late_fee, payment_method, notes, receipt_url, loyalty_reward, tip, created_at
`

type CreateAppointmentParams struct {
	ClientID pgtype.UUID        `json:"client_id"`
	ApptDate pgtype.Timestamptz `json:"appt_date"`
	Notes    pgtype.Text        `json:"notes"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment, arg.ClientID, arg.ApptDate, arg.Notes)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ApptDate,
		&i.ApptStatus,
		&i.LateFee,
		&i.PaymentMethod,
		&i.Notes,
		&i.ReceiptUrl,
		&i.LoyaltyReward,
		&i.Tip,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAppointment = `-- name: DeleteAppointment :exec
DELETE FROM appointments WHERE id = $1
`

func (q *Queries) DeleteAppointment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAppointment, id)
	return err
}

const getAppointment = `-- name: GetAppointment :one
SELECT id, client_id, appt_date, appt_status, late_fee, payment_method, notes, receipt_url, loyalty_reward, tip, created_at FROM appointments WHERE id = $1
`

func (q *Queries) GetAppointment(ctx context.Context, id pgtype.UUID) (Appointment, error) {
	row := q.db.QueryRow(ctx, getAppointment, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ApptDate,
		&i.ApptStatus,
		&i.LateFee,
		&i.PaymentMethod,
		&i.Notes,
		&i.ReceiptUrl,
		&i.LoyaltyReward,
		&i.Tip,
		&i.CreatedAt,
	)
	return i, err
}

const getAppointmentCountForPeriod = `-- name: GetAppointmentCountForPeriod :one
SELECT COUNT(*) FROM appointments
WHERE appt_status = 'complete'
  AND appt_date >= $1 AND appt_date < $2
`

type GetAppointmentCountForPeriodParams struct {
	ApptDate   pgtype.Timestamptz `json:"appt_date"`
	ApptDate_2 pgtype.Timestamptz `json:"appt_date_2"`
}

func (q *Queries) GetAppointmentCountForPeriod(ctx context.Context, arg GetAppointmentCountForPeriodParams) (int64, error) {
	row := q.db.QueryRow(ctx, getAppointmentCountForPeriod, arg.ApptDate, arg.ApptDate_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAppointmentWithClient = `-- name: GetAppointmentWithClient :one
SELECT
    appointments.id,
    appointments.client_id,
    appointments.appt_date,
    appointments.appt_status,
    appointments.late_fee,
    appointments.payment_method,
    appointments.notes,
    appointments.receipt_url,
    appointments.loyalty_reward,
    appointments.tip,
    appointments.created_at,

    clients.client_name,
    clients.contact_method,

    (
        SELECT COUNT(*)
        FROM appointments AS client_appointments
        WHERE client_appointments.client_id = appointments.client_id
          AND client_appointments.appt_status = 'complete'
    ) AS complete_appointments

FROM appointments

JOIN clients
    ON clients.id = appointments.client_id

WHERE appointments.id = $1
`

type GetAppointmentWithClientRow struct {
	ID                   pgtype.UUID        `json:"id"`
	ClientID             pgtype.UUID        `json:"client_id"`
	ApptDate             pgtype.Timestamptz `json:"appt_date"`
	ApptStatus           AppointmentStatus  `json:"appt_status"`
	LateFee              pgtype.Numeric     `json:"late_fee"`
	PaymentMethod        NullPaymentMethod  `json:"payment_method"`
	Notes                pgtype.Text        `json:"notes"`
	ReceiptUrl           pgtype.Text        `json:"receipt_url"`
	LoyaltyReward        bool               `json:"loyalty_reward"`
	Tip                  pgtype.Numeric     `json:"tip"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	ClientName           string             `json:"client_name"`
	ContactMethod        pgtype.Text        `json:"contact_method"`
	CompleteAppointments int64              `json:"complete_appointments"`
}

func (q *Queries) GetAppointmentWithClient(ctx context.Context, id pgtype.UUID) (GetAppointmentWithClientRow, error) {
	row := q.db.QueryRow(ctx, getAppointmentWithClient, id)
	var i GetAppointmentWithClientRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ApptDate,
		&i.ApptStatus,
		&i.LateFee,
		&i.PaymentMethod,
		&i.Notes,
		&i.ReceiptUrl,
		&i.LoyaltyReward,
		&i.Tip,
		&i.CreatedAt,
		&i.ClientName,
		&i.ContactMethod,
		&i.CompleteAppointments,
	)
	return i, err
}

const listAppointments = `-- name: ListAppointments :many
SELECT id, client_id, appt_date, appt_status, late_fee, payment_method, notes, receipt_url, loyalty_reward, tip, created_at FROM appointments
`

func (q *Queries) ListAppointments(ctx context.Context) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, listAppointments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Appointment{}
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ApptDate,
			&i.ApptStatus,
			&i.LateFee,
			&i.PaymentMethod,
			&i.Notes,
			&i.ReceiptUrl,
			&i.LoyaltyReward,
			&i.Tip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointmentsByDateRange = `-- name: ListAppointmentsByDateRange :many
SELECT id, client_id, appt_date, appt_status, late_fee, payment_method, notes, receipt_url, loyalty_reward, tip, created_at
FROM appointments
WHERE appt_date >= $1 AND appt_date < $2
ORDER BY appt_date ASC
`

type ListAppointmentsByDateRangeParams struct {
	ApptDate   pgtype.Timestamptz `json:"appt_date"`
	ApptDate_2 pgtype.Timestamptz `json:"appt_date_2"`
}

func (q *Queries) ListAppointmentsByDateRange(ctx context.Context, arg ListAppointmentsByDateRangeParams) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, listAppointmentsByDateRange, arg.ApptDate, arg.ApptDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Appointment{}
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ApptDate,
			&i.ApptStatus,
			&i.LateFee,
			&i.PaymentMethod,
			&i.Notes,
			&i.ReceiptUrl,
			&i.LoyaltyReward,
			&i.Tip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointmentsForCalendar = `-- name: ListAppointmentsForCalendar :many
SELECT
    appointments.id,
    appointments.appt_date,
    appointments.appt_status,
    appointments.notes,
    clients.client_name
FROM appointments
JOIN clients
    ON appointments.client_id = clients.id
WHERE appointments.appt_date >= $1
    AND appointments.appt_date < $2
    AND appointments.appt_status != 'cancelled'
    AND clients.deleted_at IS NULL
ORDER BY appointments.appt_date ASC
`

type ListAppointmentsForCalendarParams struct {
	ApptDate   pgtype.Timestamptz `json:"appt_date"`
	ApptDate_2 pgtype.Timestamptz `json:"appt_date_2"`
}

type ListAppointmentsForCalendarRow struct {
	ID         pgtype.UUID        `json:"id"`
	ApptDate   pgtype.Timestamptz `json:"appt_date"`
	ApptStatus AppointmentStatus  `json:"appt_status"`
	Notes      pgtype.Text        `json:"notes"`
	ClientName string             `json:"client_name"`
}

func (q *Queries) ListAppointmentsForCalendar(ctx context.Context, arg ListAppointmentsForCalendarParams) ([]ListAppointmentsForCalendarRow, error) {
	rows, err := q.db.Query(ctx, listAppointmentsForCalendar, arg.ApptDate, arg.ApptDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppointmentsForCalendarRow{}
	for rows.Next() {
		var i ListAppointmentsForCalendarRow
		if err := rows.Scan(
			&i.ID,
			&i.ApptDate,
			&i.ApptStatus,
			&i.Notes,
			&i.ClientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointmentsWithClient = `-- name: ListAppointmentsWithClient :many
SELECT
  appointments.id,
  appointments.appt_date,
  appointments.appt_status,
  clients.client_name
FROM appointments
JOIN clients
  ON appointments.client_id = clients.id
ORDER BY appointments.appt_date DESC
`

type ListAppointmentsWithClientRow struct {
	ID         pgtype.UUID        `json:"id"`
	ApptDate   pgtype.Timestamptz `json:"appt_date"`
	ApptStatus AppointmentStatus  `json:"appt_status"`
	ClientName string             `json:"client_name"`
}

func (q *Queries) ListAppointmentsWithClient(ctx context.Context) ([]ListAppointmentsWithClientRow, error) {
	rows, err := q.db.Query(ctx, listAppointmentsWithClient)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppointmentsWithClientRow{}
	for rows.Next() {
		var i ListAppointmentsWithClientRow
		if err := rows.Scan(
			&i.ID,
			&i.ApptDate,
			&i.ApptStatus,
			&i.ClientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompleteAppointmentsForPeriod = `-- name: ListCompleteAppointmentsForPeriod :many
SELECT id, appt_date, tip
FROM appointments
WHERE appt_status = 'complete'
  AND appt_date >= $1 AND appt_date < $2
ORDER BY appt_date ASC
`

type ListCompleteAppointmentsForPeriodParams struct {
	ApptDate   pgtype.Timestamptz `json:"appt_date"`
	ApptDate_2 pgtype.Timestamptz `json:"appt_date_2"`
}

type ListCompleteAppointmentsForPeriodRow struct {
	ID       pgtype.UUID        `json:"id"`
	ApptDate pgtype.Timestamptz `json:"appt_date"`
	Tip      pgtype.Numeric     `json:"tip"`
}

func (q *Queries) ListCompleteAppointmentsForPeriod(ctx context.Context, arg ListCompleteAppointmentsForPeriodParams) ([]ListCompleteAppointmentsForPeriodRow, error) {
	rows, err := q.db.Query(ctx, listCompleteAppointmentsForPeriod, arg.ApptDate, arg.ApptDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompleteAppointmentsForPeriodRow{}
	for rows.Next() {
		var i ListCompleteAppointmentsForPeriodRow
		if err := rows.Scan(&i.ID, &i.ApptDate, &i.Tip); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingAppointments = `-- name: ListUpcomingAppointments :many
SELECT id, client_id, appt_date, appt_status, late_fee, payment_method, notes, receipt_url, loyalty_reward, tip, created_at
FROM appointments
WHERE appt_date > now() AND appt_status != 'cancelled'
ORDER BY appt_date ASC
LIMIT 10
`

func (q *Queries) ListUpcomingAppointments(ctx context.Context) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, listUpcomingAppointments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Appointment{}
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ApptDate,
			&i.ApptStatus,
			&i.LateFee,
			&i.PaymentMethod,
			&i.Notes,
			&i.ReceiptUrl,
			&i.LoyaltyReward,
			&i.Tip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingAppointmentsForDashboard = `-- name: ListUpcomingAppointmentsForDashboard :many
SELECT
    appointments.id,
    appointments.appt_date,
    clients.client_name
FROM appointments
JOIN clients
    ON appointments.client_id = clients.id
WHERE appointments.appt_date > now()
  AND appointments.appt_status != 'cancelled'
  AND clients.deleted_at IS NULL
ORDER BY appointments.appt_date ASC
LIMIT 5
`

type ListUpcomingAppointmentsForDashboardRow struct {
	ID         pgtype.UUID        `json:"id"`
	ApptDate   pgtype.Timestamptz `json:"appt_date"`
	ClientName string             `json:"client_name"`
}

func (q *Queries) ListUpcomingAppointmentsForDashboard(ctx context.Context) ([]ListUpcomingAppointmentsForDashboardRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingAppointmentsForDashboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUpcomingAppointmentsForDashboardRow{}
	for rows.Next() {
		var i ListUpcomingAppointmentsForDashboardRow
		if err := rows.Scan(&i.ID, &i.ApptDate, &i.ClientName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppointment = `-- name: UpdateAppointment :one
UPDATE appointments
SET appt_date = $2, appt_status = $3, late_fee = $4, payment_method = $5, notes = $6, receipt_url = $7, loyalty_reward = $8, tip = $9
WHERE id = $1
RETURNING id, client_id, appt_date, appt_status, late_fee, payment_method, notes, receipt_url, loyalty_reward, tip, created_at
`

type UpdateAppointmentParams struct {
	ID            pgtype.UUID        `json:"id"`
	ApptDate      pgtype.Timestamptz `json:"appt_date"`
	ApptStatus    AppointmentStatus  `json:"appt_status"`
	LateFee       pgtype.Numeric     `json:"late_fee"`
	PaymentMethod NullPaymentMethod  `json:"payment_method"`
	Notes         pgtype.Text        `json:"notes"`
	ReceiptUrl    pgtype.Text        `json:"receipt_url"`
	LoyaltyReward bool               `json:"loyalty_reward"`
	Tip           pgtype.Numeric     `json:"tip"`
}

func (q *Queries) UpdateAppointment(ctx context.Context, arg UpdateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, updateAppointment,
		arg.ID,
		arg.ApptDate,
		arg.ApptStatus,
		arg.LateFee,
		arg.PaymentMethod,
		arg.Notes,
		arg.ReceiptUrl,
		arg.LoyaltyReward,
		arg.Tip,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ApptDate,
		&i.ApptStatus,
		&i.LateFee,
		&i.PaymentMethod,
		&i.Notes,
		&i.ReceiptUrl,
		&i.LoyaltyReward,
		&i.Tip,
		&i.CreatedAt,
	)
	return i, err
}
