// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (client_name, contact_method, notes, birthday) VALUES ($1, $2, $3, $4) RETURNING id, client_name, contact_method, notes, birthday, created_at, deleted_at
`

type CreateClientParams struct {
	ClientName    string      `json:"client_name"`
	ContactMethod pgtype.Text `json:"contact_method"`
	Notes         pgtype.Text `json:"notes"`
	Birthday      pgtype.Date `json:"birthday"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.ClientName,
		arg.ContactMethod,
		arg.Notes,
		arg.Birthday,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.ContactMethod,
		&i.Notes,
		&i.Birthday,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getClient = `-- name: GetClient :one
SELECT id, client_name, contact_method, notes, birthday, created_at, deleted_at FROM clients WHERE id = $1
`

func (q *Queries) GetClient(ctx context.Context, id pgtype.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.ContactMethod,
		&i.Notes,
		&i.Birthday,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listClientAppointments = `-- name: ListClientAppointments :many
SELECT id, appt_date, appt_status, late_fee, payment_method, notes, loyalty_reward, tip, created_at
FROM appointments
WHERE client_id = $1
ORDER BY appt_date DESC
`

type ListClientAppointmentsRow struct {
	ID            pgtype.UUID        `json:"id"`
	ApptDate      pgtype.Timestamptz `json:"appt_date"`
	ApptStatus    AppointmentStatus  `json:"appt_status"`
	LateFee       pgtype.Numeric     `json:"late_fee"`
	PaymentMethod NullPaymentMethod  `json:"payment_method"`
	Notes         pgtype.Text        `json:"notes"`
	LoyaltyReward pgtype.Bool        `json:"loyalty_reward"`
	Tip           pgtype.Numeric     `json:"tip"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListClientAppointments(ctx context.Context, clientID pgtype.UUID) ([]ListClientAppointmentsRow, error) {
	rows, err := q.db.Query(ctx, listClientAppointments, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientAppointmentsRow{}
	for rows.Next() {
		var i ListClientAppointmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ApptDate,
			&i.ApptStatus,
			&i.LateFee,
			&i.PaymentMethod,
			&i.Notes,
			&i.LoyaltyReward,
			&i.Tip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClients = `-- name: ListClients :many
SELECT id, client_name, contact_method FROM clients WHERE deleted_at IS NULL
`

type ListClientsRow struct {
	ID            pgtype.UUID `json:"id"`
	ClientName    string      `json:"client_name"`
	ContactMethod pgtype.Text `json:"contact_method"`
}

func (q *Queries) ListClients(ctx context.Context) ([]ListClientsRow, error) {
	rows, err := q.db.Query(ctx, listClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientsRow{}
	for rows.Next() {
		var i ListClientsRow
		if err := rows.Scan(&i.ID, &i.ClientName, &i.ContactMethod); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompleteClientAppointments = `-- name: ListCompleteClientAppointments :many
SELECT id, appt_date, tip
FROM appointments
WHERE client_id = $1 AND appt_status = 'complete'
ORDER BY appt_date DESC
`

type ListCompleteClientAppointmentsRow struct {
	ID       pgtype.UUID        `json:"id"`
	ApptDate pgtype.Timestamptz `json:"appt_date"`
	Tip      pgtype.Numeric     `json:"tip"`
}

func (q *Queries) ListCompleteClientAppointments(ctx context.Context, clientID pgtype.UUID) ([]ListCompleteClientAppointmentsRow, error) {
	rows, err := q.db.Query(ctx, listCompleteClientAppointments, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompleteClientAppointmentsRow{}
	for rows.Next() {
		var i ListCompleteClientAppointmentsRow
		if err := rows.Scan(&i.ID, &i.ApptDate, &i.Tip); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteClient = `-- name: SoftDeleteClient :exec
UPDATE clients SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteClient(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteClient, id)
	return err
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
SET client_name = $2, contact_method = $3, notes = $4, birthday = $5
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, client_name, contact_method, notes, birthday, created_at, deleted_at
`

type UpdateClientParams struct {
	ID            pgtype.UUID `json:"id"`
	ClientName    string      `json:"client_name"`
	ContactMethod pgtype.Text `json:"contact_method"`
	Notes         pgtype.Text `json:"notes"`
	Birthday      pgtype.Date `json:"birthday"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.ID,
		arg.ClientName,
		arg.ContactMethod,
		arg.Notes,
		arg.Birthday,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.ContactMethod,
		&i.Notes,
		&i.Birthday,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
