// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (expense_name, price, date_purchased, receipt_url) VALUES ($1, $2, $3, $4) RETURNING id, expense_name, price, date_purchased, receipt_url, created_at
`

type CreateExpenseParams struct {
	ExpenseName   string         `json:"expense_name"`
	Price         pgtype.Numeric `json:"price"`
	DatePurchased pgtype.Date    `json:"date_purchased"`
	ReceiptUrl    pgtype.Text    `json:"receipt_url"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.ExpenseName,
		arg.Price,
		arg.DatePurchased,
		arg.ReceiptUrl,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.ExpenseName,
		&i.Price,
		&i.DatePurchased,
		&i.ReceiptUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses WHERE id = $1
`

func (q *Queries) DeleteExpense(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpense, id)
	return err
}

const getExpensesForPeriod = `-- name: GetExpensesForPeriod :one
SELECT COALESCE(SUM(price), 0)::numeric AS total FROM expenses
WHERE date_purchased >= $1 AND date_purchased < $2
`

type GetExpensesForPeriodParams struct {
	DatePurchased   pgtype.Date `json:"date_purchased"`
	DatePurchased_2 pgtype.Date `json:"date_purchased_2"`
}

func (q *Queries) GetExpensesForPeriod(ctx context.Context, arg GetExpensesForPeriodParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getExpensesForPeriod, arg.DatePurchased, arg.DatePurchased_2)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const listExpenses = `-- name: ListExpenses :many
SELECT id, expense_name, price, date_purchased, receipt_url, created_at FROM expenses
`

func (q *Queries) ListExpenses(ctx context.Context) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Expense{}
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseName,
			&i.Price,
			&i.DatePurchased,
			&i.ReceiptUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
