// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AppointmentStatus string

const (
	AppointmentStatusBooked    AppointmentStatus = "booked"
	AppointmentStatusComplete  AppointmentStatus = "complete"
	AppointmentStatusNoShow    AppointmentStatus = "no_show"
	AppointmentStatusCancelled AppointmentStatus = "cancelled"
)

func (e *AppointmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppointmentStatus(s)
	case string:
		*e = AppointmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AppointmentStatus: %T", src)
	}
	return nil
}

type NullAppointmentStatus struct {
	AppointmentStatus AppointmentStatus `json:"appointment_status"`
	Valid             bool              `json:"valid"` // Valid is true if AppointmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppointmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AppointmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppointmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppointmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppointmentStatus), nil
}

type DiscountType string

const (
	DiscountTypeAmount  DiscountType = "amount"
	DiscountTypePercent DiscountType = "percent"
)

func (e *DiscountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DiscountType(s)
	case string:
		*e = DiscountType(s)
	default:
		return fmt.Errorf("unsupported scan type for DiscountType: %T", src)
	}
	return nil
}

type NullDiscountType struct {
	DiscountType DiscountType `json:"discount_type"`
	Valid        bool         `json:"valid"` // Valid is true if DiscountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDiscountType) Scan(value interface{}) error {
	if value == nil {
		ns.DiscountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DiscountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDiscountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DiscountType), nil
}

type PaymentMethod string

const (
	PaymentMethodCash    PaymentMethod = "cash"
	PaymentMethodZelle   PaymentMethod = "zelle"
	PaymentMethodCashApp PaymentMethod = "cash_app"
	PaymentMethodOther   PaymentMethod = "other"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type Appointment struct {
	ID            pgtype.UUID        `json:"id"`
	ClientID      pgtype.UUID        `json:"client_id"`
	ApptDate      pgtype.Timestamptz `json:"appt_date"`
	ApptStatus    AppointmentStatus  `json:"appt_status"`
	LateFee       pgtype.Numeric     `json:"late_fee"`
	PaymentMethod NullPaymentMethod  `json:"payment_method"`
	Notes         pgtype.Text        `json:"notes"`
	ReceiptUrl    pgtype.Text        `json:"receipt_url"`
	LoyaltyReward pgtype.Bool        `json:"loyalty_reward"`
	Tip           pgtype.Numeric     `json:"tip"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type AppointmentDiscount struct {
	ID            pgtype.UUID        `json:"id"`
	AppointmentID pgtype.UUID        `json:"appointment_id"`
	DiscountName  string             `json:"discount_name"`
	DiscountType  DiscountType       `json:"discount_type"`
	DiscountValue pgtype.Numeric     `json:"discount_value"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type AppointmentService struct {
	ID            pgtype.UUID        `json:"id"`
	AppointmentID pgtype.UUID        `json:"appointment_id"`
	ServiceName   string             `json:"service_name"`
	ServicePrice  pgtype.Numeric     `json:"service_price"`
	DesignPrice   pgtype.Numeric     `json:"design_price"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Client struct {
	ID            pgtype.UUID        `json:"id"`
	ClientName    string             `json:"client_name"`
	ContactMethod pgtype.Text        `json:"contact_method"`
	Notes         pgtype.Text        `json:"notes"`
	Birthday      pgtype.Date        `json:"birthday"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type Expense struct {
	ID            pgtype.UUID        `json:"id"`
	ExpenseName   string             `json:"expense_name"`
	Price         pgtype.Numeric     `json:"price"`
	DatePurchased pgtype.Date        `json:"date_purchased"`
	ReceiptUrl    pgtype.Text        `json:"receipt_url"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Service struct {
	ID          pgtype.UUID        `json:"id"`
	ServiceName string             `json:"service_name"`
	Price       pgtype.Numeric     `json:"price"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
