// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error)
	CreateAppointmentDiscount(ctx context.Context, arg CreateAppointmentDiscountParams) (AppointmentDiscount, error)
	CreateAppointmentService(ctx context.Context, arg CreateAppointmentServiceParams) (AppointmentService, error)
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteAppointment(ctx context.Context, id pgtype.UUID) error
	DeleteAppointmentDiscount(ctx context.Context, id pgtype.UUID) error
	DeleteAppointmentService(ctx context.Context, id pgtype.UUID) error
	DeleteExpense(ctx context.Context, id pgtype.UUID) error
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteService(ctx context.Context, id pgtype.UUID) error
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	GetAppointment(ctx context.Context, id pgtype.UUID) (Appointment, error)
	GetAppointmentCountForPeriod(ctx context.Context, arg GetAppointmentCountForPeriodParams) (int64, error)
	GetAppointmentWithClient(ctx context.Context, id pgtype.UUID) (GetAppointmentWithClientRow, error)
	GetClient(ctx context.Context, id pgtype.UUID) (Client, error)
	GetExpensesForPeriod(ctx context.Context, arg GetExpensesForPeriodParams) (pgtype.Numeric, error)
	GetSessionByID(ctx context.Context, id pgtype.UUID) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListAppointmentDiscountsByAppointment(ctx context.Context, appointmentID pgtype.UUID) ([]ListAppointmentDiscountsByAppointmentRow, error)
	ListAppointmentServicesByAppointment(ctx context.Context, appointmentID pgtype.UUID) ([]ListAppointmentServicesByAppointmentRow, error)
	ListAppointments(ctx context.Context) ([]Appointment, error)
	ListAppointmentsByDateRange(ctx context.Context, arg ListAppointmentsByDateRangeParams) ([]Appointment, error)
	ListAppointmentsForCalendar(ctx context.Context, arg ListAppointmentsForCalendarParams) ([]ListAppointmentsForCalendarRow, error)
	ListAppointmentsWithClient(ctx context.Context) ([]ListAppointmentsWithClientRow, error)
	ListClientAppointments(ctx context.Context, clientID pgtype.UUID) ([]ListClientAppointmentsRow, error)
	ListClients(ctx context.Context) ([]ListClientsRow, error)
	ListCompleteAppointmentsForPeriod(ctx context.Context, arg ListCompleteAppointmentsForPeriodParams) ([]ListCompleteAppointmentsForPeriodRow, error)
	ListCompleteClientAppointments(ctx context.Context, clientID pgtype.UUID) ([]ListCompleteClientAppointmentsRow, error)
	ListExpenses(ctx context.Context) ([]Expense, error)
	ListServices(ctx context.Context) ([]Service, error)
	ListUpcomingAppointments(ctx context.Context) ([]Appointment, error)
	ListUpcomingAppointmentsForDashboard(ctx context.Context) ([]ListUpcomingAppointmentsForDashboardRow, error)
	SoftDeleteClient(ctx context.Context, id pgtype.UUID) error
	UpdateAppointment(ctx context.Context, arg UpdateAppointmentParams) (Appointment, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error)
	UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error)
}

var _ Querier = (*Queries)(nil)
