// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createService = `-- name: CreateService :one
INSERT INTO services (service_name, price) VALUES ($1, $2) RETURNING id, service_name, price, created_at
`

type CreateServiceParams struct {
	ServiceName string         `json:"service_name"`
	Price       pgtype.Numeric `json:"price"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService, arg.ServiceName, arg.Price)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services WHERE id = $1
`

func (q *Queries) DeleteService(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteService, id)
	return err
}

const listServices = `-- name: ListServices :many
SELECT id, service_name, price, created_at FROM services
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.ServiceName,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET service_name = $2, price = $3
WHERE id = $1
RETURNING id, service_name, price, created_at
`

type UpdateServiceParams struct {
	ID          pgtype.UUID    `json:"id"`
	ServiceName string         `json:"service_name"`
	Price       pgtype.Numeric `json:"price"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService, arg.ID, arg.ServiceName, arg.Price)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}
